# Generated by Django 4.2 on 2024-08-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_otpcode_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
